
title: My Resume
url: 'https://00100100.net'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Donald  Fanning  ## put your name
title: 'Hacker & Inventor'  ## your title
location: Seattle, WA.


## Social Profiles
facebook: http://www.facebook.com/donfanning  ## your facebook account url
twitter: http://www.twitter.com/don_fanning  ## your twitter account url
linkedin: http://www.linkedin.com/in/donfanning  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
